version: '3'

includes:
  go:
    taskfile: go/taskfile.yaml
    dir: go

tasks:
  prepare:
    desc: Prepare the project
    cmds:
      - cp pj_config_site.h.in 3rdparty/pjproject/pjlib/include/pj/config_site.h
